import CherryControl
import Darwin
import Dispatch
import Foundation
import GhosttyTerminal

private let shellTransportDebugEnabled = ProcessInfo.processInfo.environment["CHERRY_DEBUG_INPUT"] == "1"

struct TerminalViewportSize: Equatable {
    let columns: Int
    let rows: Int
}

struct ShellIntegrationBootstrap {
    let zdotdir: String

    static func prepare(
        shellPath: String,
        homeDirectory: URL = FileManager.default.homeDirectoryForCurrentUser,
        fileManager: FileManager = .default
    ) throws -> ShellIntegrationBootstrap? {
        guard URL(fileURLWithPath: shellPath).lastPathComponent == "zsh" else {
            return nil
        }

        let directory = homeDirectory
            .appendingPathComponent("Library", isDirectory: true)
            .appendingPathComponent("Application Support", isDirectory: true)
            .appendingPathComponent("Cherry", isDirectory: true)
            .appendingPathComponent("ShellIntegration", isDirectory: true)
            .appendingPathComponent("zsh", isDirectory: true)

        try fileManager.createDirectory(at: directory, withIntermediateDirectories: true)

        for file in zshBootstrapFiles {
            let url = directory.appendingPathComponent(file.name, isDirectory: false)
            try file.contents.write(to: url, atomically: true, encoding: .utf8)
        }

        return ShellIntegrationBootstrap(zdotdir: directory.path)
    }

    static let zshBootstrapFiles: [(name: String, contents: String)] = [
        (
            ".zshenv",
            """
            # Generated by Cherry. Do not edit.
            if [[ -n "${CHERRY_ORIGINAL_ZDOTDIR-}" ]]; then
              export ZDOTDIR="${CHERRY_ORIGINAL_ZDOTDIR}"
            else
              unset ZDOTDIR
            fi

            if [[ -f "${ZDOTDIR:-$HOME}/.zshenv" ]]; then
              source "${ZDOTDIR:-$HOME}/.zshenv"
            fi

            export ZDOTDIR="${CHERRY_BOOTSTRAP_ZDOTDIR}"
            """
        ),
        (
            ".zprofile",
            """
            # Generated by Cherry. Do not edit.
            _cherry_original_zdotdir="${CHERRY_ORIGINAL_ZDOTDIR:-$HOME}"
            if [[ -n "${CHERRY_ORIGINAL_ZDOTDIR-}" ]]; then
              export ZDOTDIR="${CHERRY_ORIGINAL_ZDOTDIR}"
            else
              unset ZDOTDIR
            fi

            if [[ -f "$_cherry_original_zdotdir/.zprofile" ]]; then
              source "$_cherry_original_zdotdir/.zprofile"
            fi

            export ZDOTDIR="${CHERRY_BOOTSTRAP_ZDOTDIR}"
            unset _cherry_original_zdotdir
            """
        ),
        (
            ".zshrc",
            """
            # Generated by Cherry. Do not edit.
            _cherry_original_zdotdir="${CHERRY_ORIGINAL_ZDOTDIR:-$HOME}"
            if [[ -n "${CHERRY_ORIGINAL_ZDOTDIR-}" ]]; then
              export ZDOTDIR="${CHERRY_ORIGINAL_ZDOTDIR}"
            else
              unset ZDOTDIR
            fi

            if [[ -f "$_cherry_original_zdotdir/.zshrc" ]]; then
              source "$_cherry_original_zdotdir/.zshrc"
            fi
            unset _cherry_original_zdotdir

            export ZDOTDIR="${CHERRY_BOOTSTRAP_ZDOTDIR}"
            if [[ "${CHERRY_DISABLE_SHELL_INTEGRATION-}" != "1" ]]; then
              source "${CHERRY_BOOTSTRAP_ZDOTDIR}/cherry-integration.zsh"
            fi

            if [[ -n "${CHERRY_ORIGINAL_ZDOTDIR-}" ]]; then
              export ZDOTDIR="${CHERRY_ORIGINAL_ZDOTDIR}"
            else
              unset ZDOTDIR
            fi
            """
        ),
        (
            "cherry-integration.zsh",
            """
            # Generated by Cherry. Do not edit.
            if [[ -o interactive && -z "${CHERRY_ZSH_INTEGRATION_SOURCED-}" ]]; then
              typeset -g CHERRY_ZSH_INTEGRATION_SOURCED=1

              _cherry_set_title() {
                emulate -L zsh
                local title="$1"
                title="${title//$'\\e'/}"
                title="${title//$'\\a'/}"
                print -n -- $'\\e]2;'"$title"$'\\a'
              }

              _cherry_set_working_directory() {
                emulate -L zsh
                local directory="$PWD"
                directory="${directory//$'\\e'/}"
                directory="${directory//$'\\a'/}"
                # Match Ghostty's shell integration: report cwd with OSC 7
                # using the kitty-shell-cwd scheme, and report on both chpwd
                # and precmd because commands may change cwd without chpwd.
                print -n -- $'\\e]7;kitty-shell-cwd://'"$HOST$directory"$'\\a'
              }

              _cherry_emit_nix_shell_metadata() {
                emulate -L zsh
                local state="$1"
                local command="${2-}"
                command="${command//$'\\e'/}"
                command="${command//$'\\a'/}"
                print -n -- $'\\e]777;cherry-nix;'"$state"';'"$command"$'\\a'
              }

              _cherry_emit_command_metadata() {
                emulate -L zsh
                local command="$1"
                command="${command//$'\\e'/}"
                command="${command//$'\\a'/}"
                print -n -- $'\\e]777;cherry-command;'"$command"$'\\a'
              }

              _cherry_is_nix_shell_command() {
                emulate -L zsh
                setopt EXTENDED_GLOB
                local command="$1"
                local -a tokens
                tokens=("${(z)command}")
                local index=1
                local token name

                while (( index <= ${#tokens} )); do
                  token="${tokens[$index]}"
                  name="${token:t}"
                  name="${name:l}"

                  if [[ "$token" == [A-Za-z_][A-Za-z0-9_]#=* ]]; then
                    (( index++ ))
                    continue
                  fi

                  if [[ "$name" == "command" || "$name" == "exec" || "$name" == "noglob" || "$name" == "time" ]]; then
                    (( index++ ))
                    continue
                  fi

                  if [[ "$name" == "arch" ]]; then
                    (( index++ ))
                    if (( index <= ${#tokens} )) && [[ "${tokens[$index]}" == -* ]]; then
                      (( index++ ))
                    fi
                    continue
                  fi

                  if [[ "$name" == "sudo" || "$name" == "doas" ]]; then
                    (( index++ ))
                    while (( index <= ${#tokens} )) && [[ "${tokens[$index]}" == -* ]]; do
                      case "${tokens[$index]}" in
                        -C|-E|-H|-P|-S|-c|-g|-h|-p|-u|--cwd|--directory|--preserve-env|--user)
                          (( index += 2 ))
                          ;;
                        *)
                          (( index++ ))
                          ;;
                      esac
                    done
                    continue
                  fi

                  if [[ "$name" == "env" ]]; then
                    (( index++ ))
                    while (( index <= ${#tokens} )); do
                      token="${tokens[$index]}"
                      if [[ "$token" == [A-Za-z_][A-Za-z0-9_]#=* ]]; then
                        (( index++ ))
                      elif [[ "$token" == -* ]]; then
                        case "$token" in
                          -C|-S|-u|--chdir|--ignore-signal|--split-string|--unset)
                            (( index += 2 ))
                            ;;
                          *)
                            (( index++ ))
                            ;;
                        esac
                      else
                        break
                      fi
                    done
                    continue
                  fi

                  break
                done

                (( index <= ${#tokens} )) || return 1
                token="${tokens[$index]}"
                name="${token:t}"
                name="${name:l}"

                if [[ "$name" == "nix-shell" ]]; then
                  return 0
                fi
                [[ "$name" == "nix" ]] || return 1

                (( index++ ))
                while (( index <= ${#tokens} )); do
                  token="${tokens[$index]}"
                  case "$token" in
                    shell|develop)
                      return 0
                      ;;
                    --)
                      return 1
                      ;;
                    --option|--override-input)
                      (( index += 3 ))
                      ;;
                    --access-tokens|--builders|--commit-lock-file-summary|--cores|--eval-store|--experimental-features|--extra-experimental-features|--flake-registry|--log-format|--max-jobs|--store|-j)
                      (( index += 2 ))
                      ;;
                    -*)
                      (( index++ ))
                      ;;
                    *)
                      return 1
                      ;;
                  esac
                done

                return 1
              }

              # OSC 133 semantic-prompt markers, emitted only under native-PTY
              # (CHERRY_EMIT_OSC133) so the host-managed default byte stream is
              # unchanged. Ghostty parses these and fires command_finished, giving
              # precise command-boundary/idle signals for plain scripts.
              _cherry_osc133() {
                [[ -n "${CHERRY_EMIT_OSC133-}" ]] || return 0
                print -n -- "$1"
              }

              _cherry_preexec() {
                emulate -L zsh
                local typed_command="$1"
                local expanded_command="${2:-$typed_command}"
                if [[ -n "$expanded_command" && "$expanded_command" != "$typed_command" ]]; then
                  _cherry_emit_command_metadata "$expanded_command"
                fi
                _cherry_set_title "$typed_command"
                _cherry_osc133 $'\\e]133;C\\a'
                if _cherry_is_nix_shell_command "$expanded_command"; then
                  typeset -g CHERRY_NIX_SHELL_METADATA_ACTIVE=1
                  _cherry_emit_nix_shell_metadata enter "$expanded_command"

                  if [[ -n "${CHERRY_BOOTSTRAP_ZDOTDIR-}" ]]; then
                    if [[ -n "${ZDOTDIR+x}" ]]; then
                      typeset -g CHERRY_NIX_SHELL_PREVIOUS_ZDOTDIR="$ZDOTDIR"
                      typeset -g CHERRY_NIX_SHELL_PREVIOUS_ZDOTDIR_WAS_SET=1
                    else
                      unset CHERRY_NIX_SHELL_PREVIOUS_ZDOTDIR
                      typeset -g CHERRY_NIX_SHELL_PREVIOUS_ZDOTDIR_WAS_SET=0
                    fi
                    typeset -g CHERRY_NIX_SHELL_ZDOTDIR_OVERRIDE=1
                    export ZDOTDIR="${CHERRY_BOOTSTRAP_ZDOTDIR}"
                  fi
                fi
              }

              _cherry_precmd() {
                local _cherry_last_exit=$?
                emulate -L zsh
                _cherry_osc133 $'\\e]133;D;'"$_cherry_last_exit"$'\\a'
                if [[ -n "${CHERRY_NIX_SHELL_METADATA_ACTIVE-}" ]]; then
                  _cherry_emit_nix_shell_metadata exit
                  unset CHERRY_NIX_SHELL_METADATA_ACTIVE
                fi

                if [[ -n "${CHERRY_NIX_SHELL_ZDOTDIR_OVERRIDE-}" ]]; then
                  if [[ "${CHERRY_NIX_SHELL_PREVIOUS_ZDOTDIR_WAS_SET-}" == "1" ]]; then
                    export ZDOTDIR="${CHERRY_NIX_SHELL_PREVIOUS_ZDOTDIR}"
                  else
                    unset ZDOTDIR
                  fi
                  unset CHERRY_NIX_SHELL_ZDOTDIR_OVERRIDE
                  unset CHERRY_NIX_SHELL_PREVIOUS_ZDOTDIR
                  unset CHERRY_NIX_SHELL_PREVIOUS_ZDOTDIR_WAS_SET
                fi

                local directory="${PWD/#$HOME/~}"
                _cherry_set_working_directory
                _cherry_set_title "$directory"
                _cherry_osc133 $'\\e]133;A\\a'
              }

              autoload -Uz add-zsh-hook
              add-zsh-hook preexec _cherry_preexec
              add-zsh-hook chpwd _cherry_set_working_directory
              add-zsh-hook precmd _cherry_precmd
              _cherry_set_working_directory

              if [[ -n "${CHERRY_STARTUP_COMMAND-}" ]]; then
                _cherry_startup_command="$CHERRY_STARTUP_COMMAND"
                unset CHERRY_STARTUP_COMMAND
                eval "$_cherry_startup_command"
                exit $?
              fi
            fi
            """
        )
    ]
}

final class ShellProcessController: @unchecked Sendable {
    private final class IOQueueIdentity {}

    private static let ioQueueSpecificKey = DispatchSpecificKey<ObjectIdentifier>()

    struct Configuration {
        let shellPath: String
        let workingDirectory: String
        let projectRoot: String?
        let processID: String?
        let agentID: String?
        let environment: [String: String]
        let term: String
        let initialSize: TerminalViewportSize
        let startupCommand: String?

        init(
            shellPath: String,
            workingDirectory: String,
            projectRoot: String? = nil,
            processID: String? = nil,
            agentID: String? = nil,
            environment: [String: String] = [:],
            term: String,
            initialSize: TerminalViewportSize,
            startupCommand: String? = nil
        ) {
            self.shellPath = shellPath
            self.workingDirectory = workingDirectory
            self.projectRoot = projectRoot
            self.processID = processID
            self.agentID = agentID
            self.environment = environment
            self.term = term
            self.initialSize = initialSize
            self.startupCommand = startupCommand
        }
    }

    static let defaultShellPath: String = {
        if let shell = ProcessInfo.processInfo.environment["SHELL"], !shell.isEmpty {
            return shell
        }

        guard let record = getpwuid(getuid()) else {
            return "/bin/zsh"
        }

        return String(cString: record.pointee.pw_shell)
    }()

    static let defaultShellName = URL(fileURLWithPath: defaultShellPath).lastPathComponent

    /// True if `shellPID` has at least one child process — i.e. the shell is
    /// running a foreground/background program rather than idling at its prompt.
    /// The kernel-truth "is a command running" check for a plain terminal pane;
    /// works under native-PTY where the host holds no PTY fd to `tcgetpgrp`.
    static func shellHasChildProcess(shellPID: pid_t) -> Bool {
        guard shellPID > 1 else { return false }
        return enumerateProcesses().contains { $0.parentPID == shellPID }
    }

    /// Resolves the `(command, environment)` for ghostty's native EXEC backend so
    /// a libghostty-spawned shell matches the host-managed forkpty launch.
    ///
    /// IMPORTANT: this MIRRORS the forkpty child setup below (the `setenv` block
    /// ~908-953 and the `execv` argv ~956-994). Keep the two in sync — host-managed
    /// uses the forkpty path; native-PTY uses this. ghostty word-splits `command`
    /// like a shell, so the common shell-integration path returns `"<shell> -l"`
    /// and delivers the startup/agent command via `CHERRY_STARTUP_COMMAND`.
    static func nativeExecLaunch(
        for configuration: Configuration
    ) -> (command: String, environment: [String: String]) {
        let shellPath = configuration.shellPath
        let shellIntegration = try? ShellIntegrationBootstrap.prepare(shellPath: shellPath)

        let inheritedZDOTDIR = ProcessInfo.processInfo.environment["ZDOTDIR"]
        let inheritedBootstrapZDOTDIR = ProcessInfo.processInfo.environment["CHERRY_BOOTSTRAP_ZDOTDIR"]
        let originalZDOTDIR: String? = inheritedZDOTDIR == inheritedBootstrapZDOTDIR ? nil : inheritedZDOTDIR

        let extraTerminfoDirs = Self.preferredTerminfo.additionalDirs
        let inheritedTerminfoDirs = ProcessInfo.processInfo.environment["TERMINFO_DIRS"]
        let mergedTerminfoDirs: String? = {
            guard let extraTerminfoDirs, !extraTerminfoDirs.isEmpty else { return nil }
            guard let inheritedTerminfoDirs, !inheritedTerminfoDirs.isEmpty else { return extraTerminfoDirs }
            return "\(extraTerminfoDirs):\(inheritedTerminfoDirs)"
        }()

        var environment = configuration.environment
        environment["TERM"] = configuration.term
        if let mergedTerminfoDirs { environment["TERMINFO_DIRS"] = mergedTerminfoDirs }
        environment["PWD"] = configuration.workingDirectory
        environment["TERM_PROGRAM"] = "Ghostty"
        environment["CHERRY_TERM_PROGRAM"] = "Cherry"
        environment["COLORTERM"] = "truecolor"
        environment["INSIDE_CHERRY"] = "1"
        // Native-PTY only: ask the shell integration to emit OSC 133 so ghostty
        // fires command_finished. The host path leaves this unset (default byte
        // stream unchanged).
        environment["CHERRY_EMIT_OSC133"] = "1"
        if let projectRoot = configuration.projectRoot, !projectRoot.isEmpty {
            environment[CherryControl.projectRootEnvironmentKey] = projectRoot
        }
        if let processID = configuration.processID, !processID.isEmpty {
            environment[CherryControl.processIDEnvironmentKey] = processID
        }
        if let agentID = configuration.agentID, !agentID.isEmpty {
            environment[CherryControl.agentIDEnvironmentKey] = agentID
        }

        let shellCommand: String
        if let shellIntegration {
            environment["CHERRY_BOOTSTRAP_ZDOTDIR"] = shellIntegration.zdotdir
            if let startupCommand = configuration.startupCommand, !startupCommand.isEmpty {
                environment["CHERRY_STARTUP_COMMAND"] = startupCommand
            }
            if let originalZDOTDIR, !originalZDOTDIR.isEmpty {
                environment["CHERRY_ORIGINAL_ZDOTDIR"] = originalZDOTDIR
            }
            environment["ZDOTDIR"] = shellIntegration.zdotdir
            shellCommand = "\(shellPath) -l"
        } else if let startupCommand = configuration.startupCommand, !startupCommand.isEmpty {
            // No shell integration: a login+interactive shell that execs the
            // startup command (mirrors the `execv` fallback at ~956-979).
            shellCommand = "\(shellPath) -l -i -c \(singleQuoted("exec \(startupCommand)"))"
        } else {
            shellCommand = "\(shellPath) -l"
        }

        // Ghostty adds `execEnvironment` to its inherited environment; omitting a
        // key does not remove it. Cherry is often launched by an agent/tool runner
        // that sets NO_COLOR=1, which made Codex deliberately emit monochrome output
        // on the production native-PTY path. Match the host-managed forkpty path by
        // removing inherited NO_COLOR unless the project explicitly configured it.
        let command = configuration.environment["NO_COLOR"] == nil
            ? "/usr/bin/env -u NO_COLOR \(shellCommand)"
            : shellCommand

        return (command, environment)
    }

    /// POSIX single-quote a token so ghostty's shell-style splitter keeps it whole.
    private static func singleQuoted(_ value: String) -> String {
        "'" + value.replacingOccurrences(of: "'", with: "'\\''") + "'"
    }

    struct TerminfoSelection {
        let term: String
        // Colon-separated dir list to prepend to the child PTY's
        // TERMINFO_DIRS so the spawned shell resolves the same terminfo
        // entry the parent probe found.
        let additionalDirs: String?
    }

    // Ship Ghostty's terminfo entry with the library instead of probing the
    // developer machine or relying on a login shell's environment. This is the
    // same entry the embedded renderer implements and works for Dock launches.
    static let preferredTerminfo = TerminfoSelection(
        term: "xterm-ghostty",
        additionalDirs: GhosttyRuntimeResources.terminfoDirectoryURL?.path
    )

    /// Terminate the entire native-PTY (ghostty EXEC) session anchored at
    /// `anchorPID` — the shell plus every transitive descendant and everything
    /// sharing its controlling terminal — with a HUP → TERM → KILL escalation.
    ///
    /// ghostty owns the PTY and exposes no child PID, and its two weaker signals
    /// both miss a self-backgrounding server: `freeSurface` closes the PTY, which
    /// only SIGHUPs the *foreground* process group (a Go server like `tilt up`
    /// handles/ignores SIGHUP), and the old shell-only kill hit just the shell's
    /// process group — which such a server has already left via `setpgid` into its
    /// own group. Killing the whole session catches it, so agents, terminals, and
    /// commands tear down uniformly instead of leaking a process that keeps holding
    /// its ports.
    static func terminateNativeShellSession(anchorPID: pid_t) {
        guard anchorPID > 1 else { return }
        let ownPID = getpid()
        let ownSessionID = getsid(0)

        // Snapshot the session once while the PTY is still intact so a child that
        // later reparents (to launchd) or loses its tty stays on the kill list.
        let initialMembers = nativeSessionMembers(
            anchorPID: anchorPID, excludingPID: ownPID, excludingSessionID: ownSessionID
        )
        guard !initialMembers.isEmpty else { return }

        // HUP → TERM → KILL, re-enumerating each stage (unioned with the initial
        // snapshot) so late-forked children are caught too. Only Sendable values
        // (pid sets / ids) cross the async boundary.
        signalNativeSession(
            base: initialMembers, anchorPID: anchorPID,
            excludingPID: ownPID, excludingSessionID: ownSessionID, signal: SIGHUP
        )
        DispatchQueue.global(qos: .userInitiated).asyncAfter(deadline: .now() + .milliseconds(100)) {
            signalNativeSession(
                base: initialMembers, anchorPID: anchorPID,
                excludingPID: ownPID, excludingSessionID: ownSessionID, signal: SIGTERM
            )
        }
        DispatchQueue.global(qos: .userInitiated).asyncAfter(deadline: .now() + .milliseconds(700)) {
            signalNativeSession(
                base: initialMembers, anchorPID: anchorPID,
                excludingPID: ownPID, excludingSessionID: ownSessionID, signal: SIGKILL
            )
        }
    }

    private static func signalNativeSession(
        base: Set<pid_t>, anchorPID: pid_t, excludingPID: pid_t, excludingSessionID: pid_t, signal: Int32
    ) {
        let members = base.union(
            nativeSessionMembers(anchorPID: anchorPID, excludingPID: excludingPID, excludingSessionID: excludingSessionID)
        )
        for pid in members {
            _ = Darwin.kill(pid, signal)
        }
    }

    /// The anchor's session: the anchor, its transitive descendants, and every
    /// process on its controlling tty. Never includes `excludingPID` (ourselves)
    /// or anything in `excludingSessionID` (Cherry's own session) — the EXEC shell
    /// lives in its own `login`-created session, distinct from the GUI app's, so
    /// real members are never dropped.
    private static func nativeSessionMembers(
        anchorPID: pid_t, excludingPID: pid_t, excludingSessionID: pid_t
    ) -> Set<pid_t> {
        let snapshot = enumerateProcesses()
        guard let anchor = snapshot.first(where: { $0.pid == anchorPID }) else { return [] }
        var childrenByParent: [pid_t: [pid_t]] = [:]
        for proc in snapshot {
            childrenByParent[proc.parentPID, default: []].append(proc.pid)
        }
        var members: Set<pid_t> = [anchorPID]
        var stack: [pid_t] = [anchorPID]
        while let current = stack.popLast() {
            for child in childrenByParent[current] ?? [] where members.insert(child).inserted {
                stack.append(child)
            }
        }
        if anchor.controllingTTY != -1 {
            for proc in snapshot where proc.controllingTTY == anchor.controllingTTY {
                members.insert(proc.pid)
            }
        }
        return members.filter { $0 > 1 && $0 != excludingPID && getsid($0) != excludingSessionID }
    }

    private struct ProcessSnapshotEntry {
        let pid: pid_t
        let parentPID: pid_t
        let controllingTTY: dev_t
    }

    /// One-shot snapshot of every process (pid, ppid, controlling tty) via
    /// `sysctl(KERN_PROC_ALL)`. Empty on failure.
    private static func enumerateProcesses() -> [ProcessSnapshotEntry] {
        var mib: [Int32] = [CTL_KERN, KERN_PROC, KERN_PROC_ALL]
        var byteCount = 0
        guard sysctl(&mib, u_int(mib.count), nil, &byteCount, nil, 0) == 0, byteCount > 0 else {
            return []
        }
        // Over-allocate: the table can grow between the sizing and fetching calls.
        let stride = MemoryLayout<kinfo_proc>.stride
        var procs = [kinfo_proc](repeating: kinfo_proc(), count: byteCount / stride + 16)
        var fetchedBytes = procs.count * stride
        let result = procs.withUnsafeMutableBytes { buffer in
            sysctl(&mib, u_int(mib.count), buffer.baseAddress, &fetchedBytes, nil, 0)
        }
        guard result == 0 else { return [] }
        return procs.prefix(fetchedBytes / stride).map { info in
            ProcessSnapshotEntry(
                pid: info.kp_proc.p_pid,
                parentPID: info.kp_eproc.e_ppid,
                controllingTTY: info.kp_eproc.e_tdev
            )
        }
    }

    private let configuration: Configuration
    private let onData: (Data) -> Void
    private let onExit: (Int32) -> Void
    private let ioQueueIdentity = IOQueueIdentity()
    private let ioQueue = DispatchQueue(label: "Cherry.ShellProcess", qos: .userInitiated)
    private let urgentWriteQueue = DispatchQueue(label: "Cherry.ShellProcess.UrgentWrite", qos: .userInteractive)
    private let masterFDLock = NSLock()
    private let readBufferBytes = 16 * 1024
    private let maximumReadBatchBytes = 256 * 1024
    private let outputCoalesceTargetBytes = 256 * 1024
    private let outputCoalesceInterval: DispatchTimeInterval = .milliseconds(8)
    private let highVolumeReadThrottleInterval: DispatchTimeInterval = .milliseconds(1)

    private var masterFD: Int32 = -1
    private var childPID: pid_t = 0
    private var readSource: DispatchSourceRead?
    private var writeSource: DispatchSourceWrite?
    private var processSource: DispatchSourceProcess?
    private var pendingWrite = Data()
    private var pendingWriteStartOffset = 0
    private var pendingOutput = Data()
    private var isOutputFlushScheduled = false
    private var isReadSourcePaused = false
    private var isReadSourceThrottled = false
    private var isReadSourceSuspended = false
    private var exitReported = false
    private var isTerminating = false
    private var retainedUntilExit: ShellProcessController?
    private var terminationEscalationItems: [DispatchWorkItem] = []

    var processIdentifier: pid_t? {
        ioQueue.sync {
            guard childPID > 0, !exitReported else { return nil }
            return childPID
        }
    }

    init(
        configuration: Configuration,
        onData: @escaping (Data) -> Void,
        onExit: @escaping (Int32) -> Void
    ) throws {
        self.configuration = configuration
        self.onData = onData
        self.onExit = onExit
        ioQueue.setSpecific(key: Self.ioQueueSpecificKey, value: ObjectIdentifier(ioQueueIdentity))

        try launch()
    }

    deinit {
        if childPID > 0, !exitReported {
            _ = kill(childPID, SIGHUP)
            var status: Int32 = 0
            _ = waitpid(childPID, &status, WNOHANG)
        }

        writeSource?.cancel()
        isReadSourcePaused = false
        isReadSourceThrottled = false
        resumeReadSourceIfNeeded()
        setMasterFD(-1)
        readSource?.cancel()
        processSource?.cancel()
    }

    func write(_ text: String) {
        write(Data(text.utf8))
    }

    func write(_ data: Data) {
        ioQueue.async { [self] in
            guard self.masterFD >= 0 else {
                if shellTransportDebugEnabled {
                    fputs("[pty write skipped] closed fd child=\(self.childPID)\n", stderr)
                }
                return
            }
            guard !data.isEmpty else {
                if shellTransportDebugEnabled {
                    fputs("[pty write skipped] empty payload\n", stderr)
                }
                return
            }

            self.appendPendingWrite(data)
            self.flushPendingWrites()
        }
    }

    func writeUrgent(_ data: Data) {
        guard !data.isEmpty else { return }

        urgentWriteQueue.async { [self] in
            var remaining = data
            while !remaining.isEmpty {
                switch directWriteToMaster(remaining, label: "urgent write") {
                case .wrote(let byteCount):
                    remaining.removeSubrange(0..<byteCount)
                case .interrupted:
                    continue
                case .wouldBlock:
                    write(remaining)
                    return
                case .closed, .failed:
                    return
                }
            }
        }
    }

    private enum DirectWriteResult {
        case wrote(Int)
        case interrupted
        case wouldBlock
        case closed
        case failed(Int32)
    }

    private func directWriteToMaster(_ data: Data, label: String) -> DirectWriteResult {
        masterFDLock.lock()
        defer { masterFDLock.unlock() }

        guard masterFD >= 0 else {
            if shellTransportDebugEnabled {
                fputs("[pty \(label) skipped] closed fd child=\(childPID)\n", stderr)
            }
            return .closed
        }

        let written = data.withUnsafeBytes { rawBuffer -> Int in
            guard let baseAddress = rawBuffer.baseAddress else { return 0 }
            return Darwin.write(masterFD, baseAddress, rawBuffer.count)
        }

        if written > 0 {
            if shellTransportDebugEnabled {
                let chunk = data.prefix(written)
                let rendered = chunk.map { String(format: "%02x", $0) }.joined(separator: " ")
                fputs("[pty \(label)] fd=\(masterFD) bytes=\(written) data=\(rendered)\n", stderr)
            }
            return .wrote(written)
        }

        if written == 0 {
            return .wouldBlock
        }

        let writeError = errno
        if writeError == EINTR {
            return .interrupted
        }
        if writeError == EAGAIN || writeError == EWOULDBLOCK {
            return .wouldBlock
        }

        if shellTransportDebugEnabled {
            fputs("[pty \(label) error] fd=\(masterFD) errno=\(writeError)\n", stderr)
        }
        return .failed(writeError)
    }

    func resize(columns: Int, rows: Int) {
        syncOnIOQueue { [self] in
            guard self.masterFD >= 0 else { return }

            var size = winsize(
                ws_row: UInt16(rows),
                ws_col: UInt16(columns),
                ws_xpixel: 0,
                ws_ypixel: 0
            )

            _ = ioctl(self.masterFD, TIOCSWINSZ, &size)
        }
    }

    private func syncOnIOQueue(_ work: () -> Void) {
        let identity = ObjectIdentifier(ioQueueIdentity)
        if DispatchQueue.getSpecific(key: Self.ioQueueSpecificKey) == identity {
            work()
            return
        }

        ioQueue.sync(execute: work)
    }

    func pauseOutput() {
        ioQueue.async { [self] in
            guard self.readSource != nil else { return }
            self.isReadSourcePaused = true
            self.updateReadSourceSuspension()
        }
    }

    func resumeOutput() {
        ioQueue.async { [self] in
            guard self.readSource != nil else { return }
            self.isReadSourcePaused = false
            self.updateReadSourceSuspension()
        }
    }

    func terminate() {
        ioQueue.async { [self] in
            self.terminateOnQueue()
        }
    }

    private func launch() throws {
        var master: Int32 = -1
        var size = winsize(
            ws_row: UInt16(configuration.initialSize.rows),
            ws_col: UInt16(configuration.initialSize.columns),
            ws_xpixel: 0,
            ws_ypixel: 0
        )

        let shellPath = configuration.shellPath
        let shellName = URL(fileURLWithPath: shellPath).lastPathComponent
        let workingDirectory = configuration.workingDirectory
        let projectRoot = configuration.projectRoot
        let processID = configuration.processID
        let agentID = configuration.agentID
        let environment = configuration.environment
        let term = configuration.term
        let startupCommand = configuration.startupCommand
        let inheritedZDOTDIR = ProcessInfo.processInfo.environment["ZDOTDIR"]
        let inheritedCherryBootstrapZDOTDIR = ProcessInfo.processInfo.environment["CHERRY_BOOTSTRAP_ZDOTDIR"]
        let originalZDOTDIR = if inheritedZDOTDIR == inheritedCherryBootstrapZDOTDIR {
            String?.none
        } else {
            inheritedZDOTDIR
        }
        let shellIntegration = try? ShellIntegrationBootstrap.prepare(shellPath: shellPath)
        let extraTerminfoDirs = Self.preferredTerminfo.additionalDirs
        let inheritedTerminfoDirs = ProcessInfo.processInfo.environment["TERMINFO_DIRS"]
        let mergedTerminfoDirs: String? = {
            guard let extraTerminfoDirs, !extraTerminfoDirs.isEmpty else { return nil }
            guard let inheritedTerminfoDirs, !inheritedTerminfoDirs.isEmpty else { return extraTerminfoDirs }
            return "\(extraTerminfoDirs):\(inheritedTerminfoDirs)"
        }()

        let pid = forkpty(&master, nil, nil, &size)
        if pid < 0 {
            throw POSIXError(POSIXErrorCode(rawValue: errno) ?? .EIO)
        }

        if pid == 0 {
            Self.closeInheritedFileDescriptorsForChild()
            _ = chdir(workingDirectory)
            // Cherry is a color-capable terminal; do not let launcher or
            // automation environment leak NO_COLOR into interactive children.
            _ = unsetenv("NO_COLOR")
            for (name, value) in environment {
                _ = setenv(name, value, 1)
            }
            _ = setenv("TERM", term, 1)
            if let mergedTerminfoDirs {
                _ = setenv("TERMINFO_DIRS", mergedTerminfoDirs, 1)
            }
            // Keep PWD aligned with the inherited cwd, matching Ghostty's
            // launch behavior so shells preserve user-facing directory text.
            _ = setenv("PWD", workingDirectory, 1)
            // Cherry embeds Ghostty's terminal core; advertise that
            // compatibility so TUIs choose richer terminal protocols such as
            // OSC 9 notifications instead of falling back to a bare BEL.
            _ = setenv("TERM_PROGRAM", "Ghostty", 1)
            _ = setenv("CHERRY_TERM_PROGRAM", "Cherry", 1)
            _ = setenv("COLORTERM", "truecolor", 1)
            _ = setenv("INSIDE_CHERRY", "1", 1)
            if let projectRoot, !projectRoot.isEmpty {
                _ = setenv(CherryControl.projectRootEnvironmentKey, projectRoot, 1)
            } else {
                _ = unsetenv(CherryControl.projectRootEnvironmentKey)
            }
            if let processID, !processID.isEmpty {
                _ = setenv(CherryControl.processIDEnvironmentKey, processID, 1)
            } else {
                _ = unsetenv(CherryControl.processIDEnvironmentKey)
            }
            if let agentID, !agentID.isEmpty {
                _ = setenv(CherryControl.agentIDEnvironmentKey, agentID, 1)
            } else {
                _ = unsetenv(CherryControl.agentIDEnvironmentKey)
            }
            if let shellIntegration {
                _ = setenv("CHERRY_BOOTSTRAP_ZDOTDIR", shellIntegration.zdotdir, 1)
                if let startupCommand, !startupCommand.isEmpty {
                    _ = setenv("CHERRY_STARTUP_COMMAND", startupCommand, 1)
                } else {
                    _ = unsetenv("CHERRY_STARTUP_COMMAND")
                }
                if let originalZDOTDIR, !originalZDOTDIR.isEmpty {
                    _ = setenv("CHERRY_ORIGINAL_ZDOTDIR", originalZDOTDIR, 1)
                } else {
                    _ = unsetenv("CHERRY_ORIGINAL_ZDOTDIR")
                }
                _ = setenv("ZDOTDIR", shellIntegration.zdotdir, 1)
            }

            if let startupCommand, shellIntegration == nil {
                let command = "exec \(startupCommand)"
                shellPath.withCString { shellPathPointer in
                    shellName.withCString { shellNamePointer in
                        "-l".withCString { loginFlagPointer in
                            "-i".withCString { interactiveFlagPointer in
                                "-c".withCString { commandFlagPointer in
                                    command.withCString { commandPointer in
                                        var arguments: [UnsafeMutablePointer<CChar>?] = [
                                            UnsafeMutablePointer(mutating: shellNamePointer),
                                            UnsafeMutablePointer(mutating: loginFlagPointer),
                                            UnsafeMutablePointer(mutating: interactiveFlagPointer),
                                            UnsafeMutablePointer(mutating: commandFlagPointer),
                                            UnsafeMutablePointer(mutating: commandPointer),
                                            nil
                                        ]

                                        execv(shellPathPointer, &arguments)
                                    }
                                }
                            }
                        }
                    }
                }
            } else {
                shellPath.withCString { shellPathPointer in
                    shellName.withCString { shellNamePointer in
                        "-l".withCString { loginFlagPointer in
                            var arguments: [UnsafeMutablePointer<CChar>?] = [
                                UnsafeMutablePointer(mutating: shellNamePointer),
                                UnsafeMutablePointer(mutating: loginFlagPointer),
                                nil
                            ]

                            execv(shellPathPointer, &arguments)
                        }
                    }
                }
            }

            _exit(127)
        }

        setMasterFD(master)
        childPID = pid

        Self.setCloseOnExec(fileDescriptor: master)

        let currentFlags = fcntl(master, F_GETFL)
        if currentFlags >= 0 {
            _ = fcntl(master, F_SETFL, currentFlags | O_NONBLOCK)
        }

        if shellTransportDebugEnabled {
            fputs("[pty launch] pid=\(pid) fd=\(master)\n", stderr)
        }

        let readSource = DispatchSource.makeReadSource(fileDescriptor: master, queue: ioQueue)
        readSource.setEventHandler { [weak self] in
            self?.drainReadableData()
        }
        readSource.setCancelHandler { [weak self] in
            if let self {
                self.closeMasterFD(master)
            } else {
                _ = close(master)
            }
        }
        self.readSource = readSource
        isReadSourcePaused = false
        isReadSourceThrottled = false
        isReadSourceSuspended = false
        readSource.resume()

        let processSource = DispatchSource.makeProcessSource(identifier: pid, eventMask: .exit, queue: ioQueue)
        processSource.setEventHandler { [weak self] in
            self?.handleExitEvent()
        }
        self.processSource = processSource
        processSource.resume()
    }

    private func drainReadableData() {
        guard masterFD >= 0 else { return }

        var buffer = [UInt8](repeating: 0, count: readBufferBytes)
        var output = Data()
        output.reserveCapacity(maximumReadBatchBytes)
        var didCloseReadSide = false

        while output.count < maximumReadBatchBytes {
            let bytesRead = Darwin.read(masterFD, &buffer, buffer.count)
            if bytesRead > 0 {
                if shellTransportDebugEnabled {
                    fputs("[pty read] fd=\(masterFD) bytes=\(bytesRead)\n", stderr)
                }
                output.append(contentsOf: buffer.prefix(bytesRead))
                continue
            }

            if bytesRead == 0 {
                if shellTransportDebugEnabled {
                    fputs("[pty eof] fd=\(masterFD)\n", stderr)
                }
                didCloseReadSide = true
                break
            }

            if bytesRead < 0, errno == EINTR {
                continue
            }

            if bytesRead < 0, errno != EAGAIN {
                if shellTransportDebugEnabled {
                    fputs("[pty read error] fd=\(masterFD) errno=\(errno)\n", stderr)
                }
                didCloseReadSide = true
            }

            break
        }

        if !output.isEmpty {
            enqueueOutput(output)
            if output.count >= maximumReadBatchBytes {
                throttleReadSourceBriefly()
            }
        }

        if didCloseReadSide {
            handleReadSideClosed()
        }
    }

    private func handleExitEvent() {
        guard !exitReported else { return }

        var status: Int32 = 0
        let waitedPID = waitpid(childPID, &status, 0)
        guard waitedPID == childPID else {
            if waitedPID < 0, errno == ECHILD {
                exitReported = true
                cleanup()
            }
            return
        }

        finishAfterProcessExit(status: status)
    }

    private func terminateOnQueue() {
        guard !isTerminating else { return }

        isTerminating = true
        retainedUntilExit = self
        clearPendingWrite()
        cancelWriteSource()

        let terminationTargets = currentTerminationTargets()
        if !exitReported {
            Self.sendSignal(SIGHUP, to: terminationTargets)
            scheduleTerminationEscalation(for: terminationTargets)
        }

        cancelReadSource()

        switch reapChildIfAvailable() {
        case .exited(let status):
            finishAfterProcessExit(status: status)
        case .unavailable:
            exitReported = true
            cleanup()
        case .stillRunning:
            break
        }
    }

    private func handleReadSideClosed() {
        cancelReadSource()

        switch reapChildIfAvailable() {
        case .exited(let status):
            finishAfterProcessExit(status: status)
        case .unavailable:
            exitReported = true
            cleanup()
        case .stillRunning:
            if processSource == nil {
                cleanup()
            }
        }
    }

    private enum ReapResult {
        case exited(Int32)
        case stillRunning
        case unavailable
    }

    private func reapChildIfAvailable() -> ReapResult {
        guard childPID > 0, !exitReported else { return .unavailable }

        var status: Int32 = 0
        let waitedPID = waitpid(childPID, &status, WNOHANG)
        if waitedPID == childPID {
            return .exited(status)
        }

        if waitedPID == 0 {
            return .stillRunning
        }

        return errno == ECHILD ? .unavailable : .stillRunning
    }

    private func finishAfterProcessExit(status: Int32) {
        guard !exitReported else {
            cleanup()
            return
        }

        exitReported = true
        let exitCode = normalizedExitCode(status)
        if shellTransportDebugEnabled {
            fputs("[pty exit] pid=\(childPID) status=\(exitCode)\n", stderr)
        }
        flushPendingOutput()
        if !isTerminating {
            onExit(exitCode)
        }
        cleanup()
    }

    private func enqueueOutput(_ data: Data) {
        guard !data.isEmpty else { return }

        pendingOutput.append(data)
        if pendingOutput.count >= outputCoalesceTargetBytes {
            flushPendingOutput()
        } else {
            scheduleOutputFlush()
        }
    }

    private func scheduleOutputFlush() {
        guard !isOutputFlushScheduled else { return }
        isOutputFlushScheduled = true
        ioQueue.asyncAfter(deadline: .now() + outputCoalesceInterval) { [weak self] in
            self?.flushPendingOutput()
        }
    }

    private func flushPendingOutput() {
        isOutputFlushScheduled = false
        guard !pendingOutput.isEmpty else { return }

        let output = pendingOutput
        pendingOutput.removeAll(keepingCapacity: true)
        onData(output)
    }

    private func flushPendingWrites() {
        guard masterFD >= 0 else {
            clearPendingWrite()
            cancelWriteSource()
            return
        }

        while pendingWriteStartOffset < pendingWrite.count {
            let written = pendingWrite.withUnsafeBytes { rawBuffer -> Int in
                guard let baseAddress = rawBuffer.baseAddress else { return 0 }
                return Darwin.write(
                    masterFD,
                    baseAddress.advanced(by: pendingWriteStartOffset),
                    rawBuffer.count - pendingWriteStartOffset
                )
            }

            if written > 0 {
                if shellTransportDebugEnabled {
                    let chunk = pendingWrite[pendingWriteStartOffset..<(pendingWriteStartOffset + written)]
                    let rendered = chunk.map { String(format: "%02x", $0) }.joined(separator: " ")
                    fputs("[pty write] fd=\(masterFD) bytes=\(written) data=\(rendered)\n", stderr)
                }
                discardPendingWriteBytes(written)
                continue
            }

            if written == 0 {
                ensureWriteSource()
                return
            }

            let writeError = errno
            if writeError == EINTR {
                continue
            }

            if writeError == EAGAIN || writeError == EWOULDBLOCK {
                ensureWriteSource()
                return
            }

            if shellTransportDebugEnabled {
                fputs("[pty write error] fd=\(masterFD) errno=\(writeError)\n", stderr)
            }
            clearPendingWrite()
            cancelWriteSource()
            return
        }

        cancelWriteSource()
    }

    private func appendPendingWrite(_ data: Data) {
        compactPendingWriteIfNeeded(force: false)
        pendingWrite.append(data)
    }

    private func discardPendingWriteBytes(_ byteCount: Int) {
        pendingWriteStartOffset += byteCount
        compactPendingWriteIfNeeded(force: pendingWriteStartOffset == pendingWrite.count)
    }

    private func compactPendingWriteIfNeeded(force: Bool) {
        guard pendingWriteStartOffset > 0 else { return }

        if force {
            clearPendingWrite()
            return
        }

        guard pendingWriteStartOffset >= 64 * 1024,
              pendingWriteStartOffset >= pendingWrite.count / 2
        else {
            return
        }

        pendingWrite.removeSubrange(0..<pendingWriteStartOffset)
        pendingWriteStartOffset = 0
    }

    private func clearPendingWrite() {
        pendingWrite.removeAll(keepingCapacity: true)
        pendingWriteStartOffset = 0
    }

    private func ensureWriteSource() {
        guard writeSource == nil, masterFD >= 0 else { return }

        let writeSource = DispatchSource.makeWriteSource(fileDescriptor: masterFD, queue: ioQueue)
        writeSource.setEventHandler { [weak self] in
            self?.flushPendingWrites()
        }
        self.writeSource = writeSource
        writeSource.resume()
    }

    private func cancelWriteSource() {
        writeSource?.cancel()
        writeSource = nil
    }

    private func cancelReadSource() {
        isReadSourcePaused = false
        isReadSourceThrottled = false
        resumeReadSourceIfNeeded()
        setMasterFD(-1)
        readSource?.cancel()
        readSource = nil
    }

    private func throttleReadSourceBriefly() {
        guard readSource != nil, !isReadSourcePaused, !isReadSourceThrottled else { return }

        isReadSourceThrottled = true
        updateReadSourceSuspension()

        ioQueue.asyncAfter(deadline: .now() + highVolumeReadThrottleInterval) { [weak self] in
            guard let self else { return }
            self.isReadSourceThrottled = false
            self.updateReadSourceSuspension()
        }
    }

    private func updateReadSourceSuspension() {
        guard readSource != nil else { return }

        let shouldSuspend = isReadSourcePaused || isReadSourceThrottled
        if shouldSuspend, !isReadSourceSuspended {
            readSource?.suspend()
            isReadSourceSuspended = true
        } else if !shouldSuspend {
            resumeReadSourceIfNeeded()
        }
    }

    private func resumeReadSourceIfNeeded() {
        guard isReadSourceSuspended else { return }
        readSource?.resume()
        isReadSourceSuspended = false
    }

    private func setMasterFD(_ fileDescriptor: Int32) {
        masterFDLock.lock()
        masterFD = fileDescriptor
        masterFDLock.unlock()
    }

    private func closeMasterFD(_ fileDescriptor: Int32) {
        masterFDLock.lock()
        if masterFD == fileDescriptor {
            masterFD = -1
        }
        _ = close(fileDescriptor)
        masterFDLock.unlock()
    }

    private func cleanup() {
        if shellTransportDebugEnabled {
            fputs("[pty cleanup] pid=\(childPID) fd=\(masterFD)\n", stderr)
        }
        flushPendingOutput()
        if !isTerminating {
            cancelTerminationEscalation()
        }
        clearPendingWrite()
        cancelWriteSource()
        cancelReadSource()
        processSource?.cancel()
        processSource = nil
        retainedUntilExit = nil
    }

    private struct TerminationTargets {
        let processIDs: [pid_t]
        let processGroupIDs: [pid_t]
    }

    private func currentTerminationTargets() -> TerminationTargets {
        var processIDs: Set<pid_t> = []
        var processGroupIDs: Set<pid_t> = []

        if childPID > 1 {
            processIDs.insert(childPID)
            processGroupIDs.insert(childPID)
        }

        if masterFD >= 0 {
            let foregroundProcessGroupID = tcgetpgrp(masterFD)
            if foregroundProcessGroupID > 1 {
                processGroupIDs.insert(foregroundProcessGroupID)
            }
        }

        processGroupIDs.remove(getpgrp())
        return TerminationTargets(
            processIDs: Array(processIDs),
            processGroupIDs: Array(processGroupIDs)
        )
    }

    private static func sendSignal(_ signal: Int32, to targets: TerminationTargets) {
        for processGroupID in targets.processGroupIDs where processGroupID > 1 {
            _ = Darwin.kill(-processGroupID, signal)
        }

        for processID in targets.processIDs where processID > 1 {
            _ = Darwin.kill(processID, signal)
        }
    }

    private func scheduleTerminationEscalation(for targets: TerminationTargets) {
        cancelTerminationEscalation()
        scheduleTerminationSignal(SIGTERM, to: targets, after: .milliseconds(100))
        scheduleTerminationSignal(SIGKILL, to: targets, after: .milliseconds(700))
    }

    private func scheduleTerminationSignal(
        _ signal: Int32,
        to targets: TerminationTargets,
        after delay: DispatchTimeInterval
    ) {
        let item = DispatchWorkItem { [weak self] in
            Self.sendSignal(signal, to: targets)

            guard signal == SIGKILL, let self, !self.exitReported else { return }

            switch self.reapChildIfAvailable() {
            case .exited(let status):
                self.finishAfterProcessExit(status: status)
            case .unavailable:
                self.exitReported = true
                self.cleanup()
            case .stillRunning:
                break
            }
        }
        terminationEscalationItems.append(item)
        ioQueue.asyncAfter(deadline: .now() + delay, execute: item)
    }

    private func cancelTerminationEscalation() {
        terminationEscalationItems.forEach { $0.cancel() }
        terminationEscalationItems.removeAll()
    }

    private func normalizedExitCode(_ status: Int32) -> Int32 {
        let signal = status & 0x7F
        if signal == 0 {
            return (status >> 8) & 0xFF
        }

        return 128 + signal
    }

    private static func closeInheritedFileDescriptorsForChild() {
        let descriptorCapacity = 4096
        let descriptorSize = MemoryLayout<proc_fdinfo>.stride
        var descriptors = [proc_fdinfo](repeating: proc_fdinfo(), count: descriptorCapacity)
        let byteCount = descriptors.withUnsafeMutableBufferPointer { buffer -> Int32 in
            guard let baseAddress = buffer.baseAddress else { return -1 }
            return proc_pidinfo(
                getpid(),
                PROC_PIDLISTFDS,
                0,
                baseAddress,
                Int32(descriptorSize * buffer.count)
            )
        }

        guard byteCount > 0 else {
            closeInheritedFileDescriptorsByLimit()
            return
        }

        let descriptorCount = min(Int(byteCount) / descriptorSize, descriptors.count)
        for index in 0..<descriptorCount {
            let fileDescriptor = descriptors[index].proc_fd
            if fileDescriptor >= 3 {
                _ = close(fileDescriptor)
            }
        }

        if descriptorCount == descriptors.count {
            closeInheritedFileDescriptorsByLimit()
        }
    }

    private static func closeInheritedFileDescriptorsByLimit() {
        let openMax = sysconf(_SC_OPEN_MAX)
        let maximumDescriptor = openMax > 0 ? min(openMax, 16_384) : 16_384
        guard maximumDescriptor > 3 else { return }

        for fileDescriptor in 3..<Int32(maximumDescriptor) {
            _ = close(fileDescriptor)
        }
    }

    private static func setCloseOnExec(fileDescriptor: Int32) {
        let flags = fcntl(fileDescriptor, F_GETFD)
        guard flags >= 0 else { return }
        _ = fcntl(fileDescriptor, F_SETFD, flags | FD_CLOEXEC)
    }
}
